/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlinkTaskManager {
    /// Number of Flink task managers (minimum 1)
    #[serde(rename = "instances")]
    pub instances: i32,
    /// CPU quota for each Flink task manager (minimum 0.3 = 30% of 1 CPU)
    #[serde(rename = "cpus")]
    pub cpus: f32,
    /// Memory (MB) for each Flink task manager (minimum 1024 = 1 GB)
    #[serde(rename = "mem")]
    pub mem: i32,
}

impl FlinkTaskManager {
    pub fn new(instances: i32, cpus: f32, mem: i32) -> FlinkTaskManager {
        FlinkTaskManager {
            instances,
            cpus,
            mem,
        }
    }
}


