/*
 * DSH Tenant Resource Management REST API
 *
 * Resource management API for DSH
 *
 * The version of the OpenAPI document: 1.6.6
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Notification1 {
    /// true if the notification has to do with removal of the allocation, false if it relates to creation/update of the resource
    #[serde(rename = "remove")]
    pub remove: bool,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<::std::collections::HashMap<String, String>>,
}

impl Notification1 {
    pub fn new(remove: bool, message: String) -> Notification1 {
        Notification1 {
            remove,
            message,
            args: None,
        }
    }
}


